import numpy as np
from scipy.io import wavfile as wav


class AudioWave:
    """this class is used to handel audio file processing"""

    def __init__(
        self, input_file=None, output_file=r"src/Data/output.wav", verbose=False
    ):
        """this function is used to initialize the audio_processing class

        Args:
            input_file (str): the path to the input file.
                Defaults to None.
            output_file (str, optional): the path to the output file.
                Defaults to (r"src/data/output.wav").
            verbose (bool, optional): whether or not to print verbose output.
                Defaults to False.

        Raises:
            ValueError: if the input file is not a .wav file
            FileNotFoundError: if the input file is not found
            ValueError: if the input file is too long
        """
        self.output_file = output_file
        self.verbose = verbose
        self.front_trim = 0
        self.back_trim = 0
        self.noise_level = 0.1
        self.sample_rate, self.audio_data = self.read_data(input_file)
        self.data_triming()

    def get_audio_data(self):
        """Returns the audio data as a numpy array.

        Returns:
            numpy array: the audio data generated by the class
        """
        return self.audio_data

    def set_audio_data(self, new_audio_data):
        """this function sets altered audio data as the audio data of the class

        Args:
            new_audio_data (numpy array): the new audio data to be set
        """
        new_audio_data = np.concatenate((np.zeros(self.front_trim), new_audio_data))
        new_audio_data = np.concatenate((new_audio_data, np.zeros(self.back_trim)))
        self.audio_data = new_audio_data.astype(np.int16)

    def get_sample_rate(self):
        """Returns the sample rate of the audio data.

        Returns:
            int: the sample rate of the audio data
        """
        return self.sample_rate

    def read_data(self, input_file=None):
        """this function is used to convert the audiofile to a numpy array

        Raises:
            ValueError: if the input file is not a .wav file
            FileNotFoundError: if the input file is not found
        """
        if input_file[-4:] != ".wav":
            raise ValueError("input file must be a .wav file")

        try:
            sample_rate, audio_data = wav.read(input_file)
        except FileNotFoundError as exc:
            raise FileNotFoundError("input file not found") from exc

        return sample_rate, audio_data

    def data_triming(self):
        """this function trims the audio data to remove any leading or trailing zeros

        Raises:
            ValueError: if the input file is too long
        """
        self.front_trim = len(self.audio_data) - len(
            np.trim_zeros(self.audio_data, "f")
        )
        self.back_trim = len(self.audio_data) - len(np.trim_zeros(self.audio_data, "b"))

        self.audio_data = np.trim_zeros(self.audio_data)

        if len(self.audio_data) > 2**16:
            raise ValueError("input file is too long")

    def output(self, output_file=r"src/Data/output.wav"):
        """this function is used to output the new sound wave to a file.
        if no file is specified then the default file is used

        Args:
            new_sound_wave (numpy array): the new sound wave to be outputted

        Raises:
            FileNotFoundError: if the output file path is not found
        """

        try:
            wav.write(output_file, self.sample_rate, self.audio_data)
        except FileNotFoundError as exc:
            raise FileNotFoundError(
                "The specified output path does not exist."
            ) from exc
